# Colors

foreground #839496
background #282c34

color0 #4b5263
color1 #dc322f
color2 #859900
color3 #b58900
color4 #268bd2
color5 #d33682
color6 #2aa198
color7 #4b5263
color8 #BBBBBB
color9 #cb4b16
color10 #586e75
color11 #657b83
color12 #839496
color13 #6c71c4
color14 #93a1a1
color15 #fdf6e3

# Tab Bar

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground   #282c34
active_tab_background   #979eab
inactive_tab_foreground #abb2bf
inactive_tab_background #282c34

tab_title_template {index}:{title}
active_tab_title_template {title}

map ctrl+shift+down new_tab
map ctrl+shift+d close_tab
map ctrl+shift+up set_tab_title

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+0 goto_tab 10

# Fonts 

font_size 12.5

font_family      Iosevka Light
bold_font        Iosevka Bold
italic_font      Iosevka Light Italic
bold_italic_font Iosevka Bold Italic

disable_ligatures never
font_features none

map alt+1 disable_ligatures_in active always
map alt+2 disable_ligatures_in all never
map alt+3 disable_ligatures_in tab cursor

detect_urls yes

url_color #7B8887
url_style curly

url_prefixes http https file ftp gemini irc gopher mailto news git

open_url_with default

copy_on_select no
enable_audio_bell no

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v  paste_from_clipboard
